### PR TITLE
Too many arguments for echo_block

### PR DESCRIPTION
**Pull request by krizon**
| Q             | A
| ------------- | ---
| Bug fix?      | yes
| New feature?  | no
| BC breaks?    | no
| Deprecations? | no
| Tests pass?   | yes
| Fixed tickets | -
| License       | MIT
| Doc PR        | -

The call to `echo_block()` has too many arguments by adding the `true` as fourth argument. Removed the fourth argument to match function signature.

Not sure to threat it like a bug and propose this PR to the another branch?

### CODE REVIEW

**Comment by krizon** [comment]
The failed CS check is unrelated to this PR and is fixed in #214

**Comment by fabpot** [comment]
Thank you @krizon.
